server:
  port: 8081

spring:
  application:    name: fornecedor  jpa:    hibernate:      ddl-auto: create
  datasource:    url: jdbc:mysql://192.168.0.111:3306/fornecedor
    username: administrador
    password: senhasenha
  

eureka:  client:
    register-with-eureka: true    fetch-registry: true    service-url: 
      defaultZone: http://localhost:8761/eureka      